// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// Confidence is an object representing the database table.
type Confidence struct {
	ID              int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt       null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt       null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt       null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	Score           null.Int    `boil:"score" json:"score,omitempty" toml:"score" yaml:"score,omitempty"`
	DetectionMethod null.String `boil:"detection_method" json:"detection_method,omitempty" toml:"detection_method" yaml:"detection_method,omitempty"`

	R *confidenceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L confidenceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// confidenceR is where relationships are stored.
type confidenceR struct {
}

// confidenceL is where Load methods for each relationship are stored.
type confidenceL struct{}

var (
	confidenceColumns               = []string{"id", "created_at", "updated_at", "deleted_at", "score", "detection_method"}
	confidenceColumnsWithoutDefault = []string{"created_at", "updated_at", "deleted_at", "score", "detection_method"}
	confidenceColumnsWithDefault    = []string{"id"}
	confidencePrimaryKeyColumns     = []string{"id"}
)

type (
	// ConfidenceSlice is an alias for a slice of pointers to Confidence.
	// This should generally be used opposed to []Confidence.
	ConfidenceSlice []*Confidence
	// ConfidenceHook is the signature for custom Confidence hook methods
	ConfidenceHook func(boil.Executor, *Confidence) error

	confidenceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	confidenceType                 = reflect.TypeOf(&Confidence{})
	confidenceMapping              = queries.MakeStructMapping(confidenceType)
	confidencePrimaryKeyMapping, _ = queries.BindMapping(confidenceType, confidenceMapping, confidencePrimaryKeyColumns)
	confidenceInsertCacheMut       sync.RWMutex
	confidenceInsertCache          = make(map[string]insertCache)
	confidenceUpdateCacheMut       sync.RWMutex
	confidenceUpdateCache          = make(map[string]updateCache)
	confidenceUpsertCacheMut       sync.RWMutex
	confidenceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var confidenceBeforeInsertHooks []ConfidenceHook
var confidenceBeforeUpdateHooks []ConfidenceHook
var confidenceBeforeDeleteHooks []ConfidenceHook
var confidenceBeforeUpsertHooks []ConfidenceHook

var confidenceAfterInsertHooks []ConfidenceHook
var confidenceAfterSelectHooks []ConfidenceHook
var confidenceAfterUpdateHooks []ConfidenceHook
var confidenceAfterDeleteHooks []ConfidenceHook
var confidenceAfterUpsertHooks []ConfidenceHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Confidence) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range confidenceBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Confidence) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range confidenceBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Confidence) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range confidenceBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Confidence) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range confidenceBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Confidence) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range confidenceAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Confidence) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range confidenceAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Confidence) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range confidenceAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Confidence) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range confidenceAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Confidence) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range confidenceAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddConfidenceHook registers your hook function for all future operations.
func AddConfidenceHook(hookPoint boil.HookPoint, confidenceHook ConfidenceHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		confidenceBeforeInsertHooks = append(confidenceBeforeInsertHooks, confidenceHook)
	case boil.BeforeUpdateHook:
		confidenceBeforeUpdateHooks = append(confidenceBeforeUpdateHooks, confidenceHook)
	case boil.BeforeDeleteHook:
		confidenceBeforeDeleteHooks = append(confidenceBeforeDeleteHooks, confidenceHook)
	case boil.BeforeUpsertHook:
		confidenceBeforeUpsertHooks = append(confidenceBeforeUpsertHooks, confidenceHook)
	case boil.AfterInsertHook:
		confidenceAfterInsertHooks = append(confidenceAfterInsertHooks, confidenceHook)
	case boil.AfterSelectHook:
		confidenceAfterSelectHooks = append(confidenceAfterSelectHooks, confidenceHook)
	case boil.AfterUpdateHook:
		confidenceAfterUpdateHooks = append(confidenceAfterUpdateHooks, confidenceHook)
	case boil.AfterDeleteHook:
		confidenceAfterDeleteHooks = append(confidenceAfterDeleteHooks, confidenceHook)
	case boil.AfterUpsertHook:
		confidenceAfterUpsertHooks = append(confidenceAfterUpsertHooks, confidenceHook)
	}
}

// OneP returns a single confidence record from the query, and panics on error.
func (q confidenceQuery) OneP() *Confidence {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single confidence record from the query.
func (q confidenceQuery) One() (*Confidence, error) {
	o := &Confidence{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for confidences")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Confidence records from the query, and panics on error.
func (q confidenceQuery) AllP() ConfidenceSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Confidence records from the query.
func (q confidenceQuery) All() (ConfidenceSlice, error) {
	var o []*Confidence

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Confidence slice")
	}

	if len(confidenceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Confidence records in the query, and panics on error.
func (q confidenceQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Confidence records in the query.
func (q confidenceQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count confidences rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q confidenceQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q confidenceQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if confidences exists")
	}

	return count > 0, nil
}

// ConfidencesG retrieves all records.
func ConfidencesG(mods ...qm.QueryMod) confidenceQuery {
	return Confidences(boil.GetDB(), mods...)
}

// Confidences retrieves all the records using an executor.
func Confidences(exec boil.Executor, mods ...qm.QueryMod) confidenceQuery {
	mods = append(mods, qm.From("\"confidences\""))
	return confidenceQuery{NewQuery(exec, mods...)}
}

// FindConfidenceG retrieves a single record by ID.
func FindConfidenceG(id int, selectCols ...string) (*Confidence, error) {
	return FindConfidence(boil.GetDB(), id, selectCols...)
}

// FindConfidenceGP retrieves a single record by ID, and panics on error.
func FindConfidenceGP(id int, selectCols ...string) *Confidence {
	retobj, err := FindConfidence(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindConfidence retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindConfidence(exec boil.Executor, id int, selectCols ...string) (*Confidence, error) {
	confidenceObj := &Confidence{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"confidences\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(confidenceObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from confidences")
	}

	return confidenceObj, nil
}

// FindConfidenceP retrieves a single record by ID with an executor, and panics on error.
func FindConfidenceP(exec boil.Executor, id int, selectCols ...string) *Confidence {
	retobj, err := FindConfidence(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Confidence) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Confidence) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Confidence) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Confidence) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no confidences provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.Time.IsZero() {
		o.UpdatedAt.Time = currTime
		o.UpdatedAt.Valid = true
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(confidenceColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	confidenceInsertCacheMut.RLock()
	cache, cached := confidenceInsertCache[key]
	confidenceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			confidenceColumns,
			confidenceColumnsWithDefault,
			confidenceColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(confidenceType, confidenceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(confidenceType, confidenceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"confidences\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"confidences\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into confidences")
	}

	if !cached {
		confidenceInsertCacheMut.Lock()
		confidenceInsertCache[key] = cache
		confidenceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Confidence record. See Update for
// whitelist behavior description.
func (o *Confidence) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Confidence record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Confidence) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Confidence, and panics on error.
// See Update for whitelist behavior description.
func (o *Confidence) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Confidence.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Confidence) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	confidenceUpdateCacheMut.RLock()
	cache, cached := confidenceUpdateCache[key]
	confidenceUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			confidenceColumns,
			confidencePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update confidences, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"confidences\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, confidencePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(confidenceType, confidenceMapping, append(wl, confidencePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update confidences row")
	}

	if !cached {
		confidenceUpdateCacheMut.Lock()
		confidenceUpdateCache[key] = cache
		confidenceUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q confidenceQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q confidenceQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for confidences")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ConfidenceSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o ConfidenceSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o ConfidenceSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ConfidenceSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), confidencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"confidences\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, confidencePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in confidence slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Confidence) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Confidence) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Confidence) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Confidence) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no confidences provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(confidenceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	confidenceUpsertCacheMut.RLock()
	cache, cached := confidenceUpsertCache[key]
	confidenceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			confidenceColumns,
			confidenceColumnsWithDefault,
			confidenceColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			confidenceColumns,
			confidencePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert confidences, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(confidencePrimaryKeyColumns))
			copy(conflict, confidencePrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"confidences\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(confidenceType, confidenceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(confidenceType, confidenceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert confidences")
	}

	if !cached {
		confidenceUpsertCacheMut.Lock()
		confidenceUpsertCache[key] = cache
		confidenceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Confidence record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Confidence) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Confidence record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Confidence) DeleteG() error {
	if o == nil {
		return errors.New("models: no Confidence provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Confidence record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Confidence) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Confidence record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Confidence) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Confidence provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), confidencePrimaryKeyMapping)
	sql := "DELETE FROM \"confidences\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from confidences")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q confidenceQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q confidenceQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no confidenceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from confidences")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o ConfidenceSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o ConfidenceSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Confidence slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o ConfidenceSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ConfidenceSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Confidence slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(confidenceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), confidencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"confidences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, confidencePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from confidence slice")
	}

	if len(confidenceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Confidence) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Confidence) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Confidence) ReloadG() error {
	if o == nil {
		return errors.New("models: no Confidence provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Confidence) Reload(exec boil.Executor) error {
	ret, err := FindConfidence(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ConfidenceSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *ConfidenceSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ConfidenceSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty ConfidenceSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ConfidenceSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	confidences := ConfidenceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), confidencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"confidences\".* FROM \"confidences\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, confidencePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&confidences)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ConfidenceSlice")
	}

	*o = confidences

	return nil
}

// ConfidenceExists checks if the Confidence row exists.
func ConfidenceExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"confidences\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if confidences exists")
	}

	return exists, nil
}

// ConfidenceExistsG checks if the Confidence row exists.
func ConfidenceExistsG(id int) (bool, error) {
	return ConfidenceExists(boil.GetDB(), id)
}

// ConfidenceExistsGP checks if the Confidence row exists. Panics on error.
func ConfidenceExistsGP(id int) bool {
	e, err := ConfidenceExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// ConfidenceExistsP checks if the Confidence row exists. Panics on error.
func ConfidenceExistsP(exec boil.Executor, id int) bool {
	e, err := ConfidenceExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
