// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// Cpe is an object representing the database table.
type Cpe struct {
	ID           int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt    null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt    null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt    null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	JVNID        null.Int    `boil:"jvn_id" json:"jvn_id,omitempty" toml:"jvn_id" yaml:"jvn_id,omitempty"`
	NVDID        null.Int    `boil:"nvd_id" json:"nvd_id,omitempty" toml:"nvd_id" yaml:"nvd_id,omitempty"`
	CpeName      null.String `boil:"cpe_name" json:"cpe_name,omitempty" toml:"cpe_name" yaml:"cpe_name,omitempty"`
	Part         null.String `boil:"part" json:"part,omitempty" toml:"part" yaml:"part,omitempty"`
	Vendor       null.String `boil:"vendor" json:"vendor,omitempty" toml:"vendor" yaml:"vendor,omitempty"`
	Product      null.String `boil:"product" json:"product,omitempty" toml:"product" yaml:"product,omitempty"`
	Version      null.String `boil:"version" json:"version,omitempty" toml:"version" yaml:"version,omitempty"`
	VendorUpdate null.String `boil:"vendor_update" json:"vendor_update,omitempty" toml:"vendor_update" yaml:"vendor_update,omitempty"`
	Edition      null.String `boil:"edition" json:"edition,omitempty" toml:"edition" yaml:"edition,omitempty"`
	Language     null.String `boil:"language" json:"language,omitempty" toml:"language" yaml:"language,omitempty"`

	R *cpeR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L cpeL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// cpeR is where relationships are stored.
type cpeR struct {
}

// cpeL is where Load methods for each relationship are stored.
type cpeL struct{}

var (
	cpeColumns               = []string{"id", "created_at", "updated_at", "deleted_at", "jvn_id", "nvd_id", "cpe_name", "part", "vendor", "product", "version", "vendor_update", "edition", "language"}
	cpeColumnsWithoutDefault = []string{"created_at", "updated_at", "deleted_at", "jvn_id", "nvd_id", "cpe_name", "part", "vendor", "product", "version", "vendor_update", "edition", "language"}
	cpeColumnsWithDefault    = []string{"id"}
	cpePrimaryKeyColumns     = []string{"id"}
)

type (
	// CpeSlice is an alias for a slice of pointers to Cpe.
	// This should generally be used opposed to []Cpe.
	CpeSlice []*Cpe
	// CpeHook is the signature for custom Cpe hook methods
	CpeHook func(boil.Executor, *Cpe) error

	cpeQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	cpeType                 = reflect.TypeOf(&Cpe{})
	cpeMapping              = queries.MakeStructMapping(cpeType)
	cpePrimaryKeyMapping, _ = queries.BindMapping(cpeType, cpeMapping, cpePrimaryKeyColumns)
	cpeInsertCacheMut       sync.RWMutex
	cpeInsertCache          = make(map[string]insertCache)
	cpeUpdateCacheMut       sync.RWMutex
	cpeUpdateCache          = make(map[string]updateCache)
	cpeUpsertCacheMut       sync.RWMutex
	cpeUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var cpeBeforeInsertHooks []CpeHook
var cpeBeforeUpdateHooks []CpeHook
var cpeBeforeDeleteHooks []CpeHook
var cpeBeforeUpsertHooks []CpeHook

var cpeAfterInsertHooks []CpeHook
var cpeAfterSelectHooks []CpeHook
var cpeAfterUpdateHooks []CpeHook
var cpeAfterDeleteHooks []CpeHook
var cpeAfterUpsertHooks []CpeHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Cpe) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range cpeBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Cpe) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range cpeBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Cpe) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range cpeBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Cpe) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range cpeBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Cpe) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range cpeAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Cpe) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range cpeAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Cpe) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range cpeAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Cpe) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range cpeAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Cpe) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range cpeAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddCpeHook registers your hook function for all future operations.
func AddCpeHook(hookPoint boil.HookPoint, cpeHook CpeHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		cpeBeforeInsertHooks = append(cpeBeforeInsertHooks, cpeHook)
	case boil.BeforeUpdateHook:
		cpeBeforeUpdateHooks = append(cpeBeforeUpdateHooks, cpeHook)
	case boil.BeforeDeleteHook:
		cpeBeforeDeleteHooks = append(cpeBeforeDeleteHooks, cpeHook)
	case boil.BeforeUpsertHook:
		cpeBeforeUpsertHooks = append(cpeBeforeUpsertHooks, cpeHook)
	case boil.AfterInsertHook:
		cpeAfterInsertHooks = append(cpeAfterInsertHooks, cpeHook)
	case boil.AfterSelectHook:
		cpeAfterSelectHooks = append(cpeAfterSelectHooks, cpeHook)
	case boil.AfterUpdateHook:
		cpeAfterUpdateHooks = append(cpeAfterUpdateHooks, cpeHook)
	case boil.AfterDeleteHook:
		cpeAfterDeleteHooks = append(cpeAfterDeleteHooks, cpeHook)
	case boil.AfterUpsertHook:
		cpeAfterUpsertHooks = append(cpeAfterUpsertHooks, cpeHook)
	}
}

// OneP returns a single cpe record from the query, and panics on error.
func (q cpeQuery) OneP() *Cpe {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single cpe record from the query.
func (q cpeQuery) One() (*Cpe, error) {
	o := &Cpe{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for cpes")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Cpe records from the query, and panics on error.
func (q cpeQuery) AllP() CpeSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Cpe records from the query.
func (q cpeQuery) All() (CpeSlice, error) {
	var o []*Cpe

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Cpe slice")
	}

	if len(cpeAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Cpe records in the query, and panics on error.
func (q cpeQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Cpe records in the query.
func (q cpeQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count cpes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q cpeQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q cpeQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if cpes exists")
	}

	return count > 0, nil
}

// CpesG retrieves all records.
func CpesG(mods ...qm.QueryMod) cpeQuery {
	return Cpes(boil.GetDB(), mods...)
}

// Cpes retrieves all the records using an executor.
func Cpes(exec boil.Executor, mods ...qm.QueryMod) cpeQuery {
	mods = append(mods, qm.From("\"cpes\""))
	return cpeQuery{NewQuery(exec, mods...)}
}

// FindCpeG retrieves a single record by ID.
func FindCpeG(id int, selectCols ...string) (*Cpe, error) {
	return FindCpe(boil.GetDB(), id, selectCols...)
}

// FindCpeGP retrieves a single record by ID, and panics on error.
func FindCpeGP(id int, selectCols ...string) *Cpe {
	retobj, err := FindCpe(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindCpe retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindCpe(exec boil.Executor, id int, selectCols ...string) (*Cpe, error) {
	cpeObj := &Cpe{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"cpes\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(cpeObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from cpes")
	}

	return cpeObj, nil
}

// FindCpeP retrieves a single record by ID with an executor, and panics on error.
func FindCpeP(exec boil.Executor, id int, selectCols ...string) *Cpe {
	retobj, err := FindCpe(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Cpe) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Cpe) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Cpe) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Cpe) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no cpes provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.Time.IsZero() {
		o.UpdatedAt.Time = currTime
		o.UpdatedAt.Valid = true
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(cpeColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	cpeInsertCacheMut.RLock()
	cache, cached := cpeInsertCache[key]
	cpeInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			cpeColumns,
			cpeColumnsWithDefault,
			cpeColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(cpeType, cpeMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(cpeType, cpeMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"cpes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"cpes\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into cpes")
	}

	if !cached {
		cpeInsertCacheMut.Lock()
		cpeInsertCache[key] = cache
		cpeInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Cpe record. See Update for
// whitelist behavior description.
func (o *Cpe) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Cpe record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Cpe) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Cpe, and panics on error.
// See Update for whitelist behavior description.
func (o *Cpe) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Cpe.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Cpe) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	cpeUpdateCacheMut.RLock()
	cache, cached := cpeUpdateCache[key]
	cpeUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			cpeColumns,
			cpePrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update cpes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"cpes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, cpePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(cpeType, cpeMapping, append(wl, cpePrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update cpes row")
	}

	if !cached {
		cpeUpdateCacheMut.Lock()
		cpeUpdateCache[key] = cache
		cpeUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q cpeQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q cpeQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for cpes")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o CpeSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o CpeSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o CpeSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o CpeSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cpePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"cpes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, cpePrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in cpe slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Cpe) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Cpe) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Cpe) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Cpe) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no cpes provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(cpeColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	cpeUpsertCacheMut.RLock()
	cache, cached := cpeUpsertCache[key]
	cpeUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			cpeColumns,
			cpeColumnsWithDefault,
			cpeColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			cpeColumns,
			cpePrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert cpes, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(cpePrimaryKeyColumns))
			copy(conflict, cpePrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"cpes\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(cpeType, cpeMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(cpeType, cpeMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert cpes")
	}

	if !cached {
		cpeUpsertCacheMut.Lock()
		cpeUpsertCache[key] = cache
		cpeUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Cpe record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Cpe) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Cpe record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Cpe) DeleteG() error {
	if o == nil {
		return errors.New("models: no Cpe provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Cpe record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Cpe) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Cpe record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Cpe) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Cpe provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cpePrimaryKeyMapping)
	sql := "DELETE FROM \"cpes\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from cpes")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q cpeQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q cpeQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no cpeQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from cpes")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o CpeSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o CpeSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Cpe slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o CpeSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o CpeSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Cpe slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(cpeBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cpePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"cpes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, cpePrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from cpe slice")
	}

	if len(cpeAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Cpe) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Cpe) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Cpe) ReloadG() error {
	if o == nil {
		return errors.New("models: no Cpe provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Cpe) Reload(exec boil.Executor) error {
	ret, err := FindCpe(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *CpeSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *CpeSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CpeSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty CpeSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *CpeSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	cpes := CpeSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), cpePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"cpes\".* FROM \"cpes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, cpePrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&cpes)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in CpeSlice")
	}

	*o = cpes

	return nil
}

// CpeExists checks if the Cpe row exists.
func CpeExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"cpes\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if cpes exists")
	}

	return exists, nil
}

// CpeExistsG checks if the Cpe row exists.
func CpeExistsG(id int) (bool, error) {
	return CpeExists(boil.GetDB(), id)
}

// CpeExistsGP checks if the Cpe row exists. Panics on error.
func CpeExistsGP(id int) bool {
	e, err := CpeExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// CpeExistsP checks if the Cpe row exists. Panics on error.
func CpeExistsP(exec boil.Executor, id int) bool {
	e, err := CpeExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
