// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"gopkg.in/nullbio/null.v6"
)

// Platform is an object representing the database table.
type Platform struct {
	ID         int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt  null.Time   `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt  null.Time   `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt  null.Time   `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	Name       null.String `boil:"name" json:"name,omitempty" toml:"name" yaml:"name,omitempty"`
	InstanceID null.String `boil:"instance_id" json:"instance_id,omitempty" toml:"instance_id" yaml:"instance_id,omitempty"`

	R *platformR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L platformL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// platformR is where relationships are stored.
type platformR struct {
}

// platformL is where Load methods for each relationship are stored.
type platformL struct{}

var (
	platformColumns               = []string{"id", "created_at", "updated_at", "deleted_at", "name", "instance_id"}
	platformColumnsWithoutDefault = []string{"created_at", "updated_at", "deleted_at", "name", "instance_id"}
	platformColumnsWithDefault    = []string{"id"}
	platformPrimaryKeyColumns     = []string{"id"}
)

type (
	// PlatformSlice is an alias for a slice of pointers to Platform.
	// This should generally be used opposed to []Platform.
	PlatformSlice []*Platform
	// PlatformHook is the signature for custom Platform hook methods
	PlatformHook func(boil.Executor, *Platform) error

	platformQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	platformType                 = reflect.TypeOf(&Platform{})
	platformMapping              = queries.MakeStructMapping(platformType)
	platformPrimaryKeyMapping, _ = queries.BindMapping(platformType, platformMapping, platformPrimaryKeyColumns)
	platformInsertCacheMut       sync.RWMutex
	platformInsertCache          = make(map[string]insertCache)
	platformUpdateCacheMut       sync.RWMutex
	platformUpdateCache          = make(map[string]updateCache)
	platformUpsertCacheMut       sync.RWMutex
	platformUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var platformBeforeInsertHooks []PlatformHook
var platformBeforeUpdateHooks []PlatformHook
var platformBeforeDeleteHooks []PlatformHook
var platformBeforeUpsertHooks []PlatformHook

var platformAfterInsertHooks []PlatformHook
var platformAfterSelectHooks []PlatformHook
var platformAfterUpdateHooks []PlatformHook
var platformAfterDeleteHooks []PlatformHook
var platformAfterUpsertHooks []PlatformHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Platform) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range platformBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Platform) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range platformBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Platform) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range platformBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Platform) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range platformBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Platform) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range platformAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Platform) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range platformAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Platform) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range platformAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Platform) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range platformAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Platform) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range platformAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPlatformHook registers your hook function for all future operations.
func AddPlatformHook(hookPoint boil.HookPoint, platformHook PlatformHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		platformBeforeInsertHooks = append(platformBeforeInsertHooks, platformHook)
	case boil.BeforeUpdateHook:
		platformBeforeUpdateHooks = append(platformBeforeUpdateHooks, platformHook)
	case boil.BeforeDeleteHook:
		platformBeforeDeleteHooks = append(platformBeforeDeleteHooks, platformHook)
	case boil.BeforeUpsertHook:
		platformBeforeUpsertHooks = append(platformBeforeUpsertHooks, platformHook)
	case boil.AfterInsertHook:
		platformAfterInsertHooks = append(platformAfterInsertHooks, platformHook)
	case boil.AfterSelectHook:
		platformAfterSelectHooks = append(platformAfterSelectHooks, platformHook)
	case boil.AfterUpdateHook:
		platformAfterUpdateHooks = append(platformAfterUpdateHooks, platformHook)
	case boil.AfterDeleteHook:
		platformAfterDeleteHooks = append(platformAfterDeleteHooks, platformHook)
	case boil.AfterUpsertHook:
		platformAfterUpsertHooks = append(platformAfterUpsertHooks, platformHook)
	}
}

// OneP returns a single platform record from the query, and panics on error.
func (q platformQuery) OneP() *Platform {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single platform record from the query.
func (q platformQuery) One() (*Platform, error) {
	o := &Platform{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for platforms")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all Platform records from the query, and panics on error.
func (q platformQuery) AllP() PlatformSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all Platform records from the query.
func (q platformQuery) All() (PlatformSlice, error) {
	var o []*Platform

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Platform slice")
	}

	if len(platformAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all Platform records in the query, and panics on error.
func (q platformQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all Platform records in the query.
func (q platformQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count platforms rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q platformQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q platformQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if platforms exists")
	}

	return count > 0, nil
}

// PlatformsG retrieves all records.
func PlatformsG(mods ...qm.QueryMod) platformQuery {
	return Platforms(boil.GetDB(), mods...)
}

// Platforms retrieves all the records using an executor.
func Platforms(exec boil.Executor, mods ...qm.QueryMod) platformQuery {
	mods = append(mods, qm.From("\"platforms\""))
	return platformQuery{NewQuery(exec, mods...)}
}

// FindPlatformG retrieves a single record by ID.
func FindPlatformG(id int, selectCols ...string) (*Platform, error) {
	return FindPlatform(boil.GetDB(), id, selectCols...)
}

// FindPlatformGP retrieves a single record by ID, and panics on error.
func FindPlatformGP(id int, selectCols ...string) *Platform {
	retobj, err := FindPlatform(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindPlatform retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPlatform(exec boil.Executor, id int, selectCols ...string) (*Platform, error) {
	platformObj := &Platform{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"platforms\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(platformObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from platforms")
	}

	return platformObj, nil
}

// FindPlatformP retrieves a single record by ID with an executor, and panics on error.
func FindPlatformP(exec boil.Executor, id int, selectCols ...string) *Platform {
	retobj, err := FindPlatform(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *Platform) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *Platform) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *Platform) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *Platform) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no platforms provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.Time.IsZero() {
		o.UpdatedAt.Time = currTime
		o.UpdatedAt.Valid = true
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(platformColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	platformInsertCacheMut.RLock()
	cache, cached := platformInsertCache[key]
	platformInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			platformColumns,
			platformColumnsWithDefault,
			platformColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(platformType, platformMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(platformType, platformMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"platforms\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"platforms\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into platforms")
	}

	if !cached {
		platformInsertCacheMut.Lock()
		platformInsertCache[key] = cache
		platformInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single Platform record. See Update for
// whitelist behavior description.
func (o *Platform) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single Platform record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *Platform) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the Platform, and panics on error.
// See Update for whitelist behavior description.
func (o *Platform) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the Platform.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *Platform) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	platformUpdateCacheMut.RLock()
	cache, cached := platformUpdateCache[key]
	platformUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			platformColumns,
			platformPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update platforms, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"platforms\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, platformPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(platformType, platformMapping, append(wl, platformPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update platforms row")
	}

	if !cached {
		platformUpdateCacheMut.Lock()
		platformUpdateCache[key] = cache
		platformUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q platformQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q platformQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for platforms")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o PlatformSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o PlatformSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o PlatformSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PlatformSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), platformPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"platforms\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, platformPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in platform slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *Platform) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *Platform) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *Platform) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *Platform) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no platforms provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(platformColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	platformUpsertCacheMut.RLock()
	cache, cached := platformUpsertCache[key]
	platformUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			platformColumns,
			platformColumnsWithDefault,
			platformColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			platformColumns,
			platformPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert platforms, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(platformPrimaryKeyColumns))
			copy(conflict, platformPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"platforms\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(platformType, platformMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(platformType, platformMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert platforms")
	}

	if !cached {
		platformUpsertCacheMut.Lock()
		platformUpsertCache[key] = cache
		platformUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single Platform record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Platform) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single Platform record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *Platform) DeleteG() error {
	if o == nil {
		return errors.New("models: no Platform provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single Platform record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *Platform) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single Platform record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Platform) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Platform provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), platformPrimaryKeyMapping)
	sql := "DELETE FROM \"platforms\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from platforms")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q platformQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q platformQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no platformQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from platforms")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o PlatformSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o PlatformSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no Platform slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o PlatformSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PlatformSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no Platform slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(platformBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), platformPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"platforms\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, platformPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from platform slice")
	}

	if len(platformAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *Platform) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *Platform) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *Platform) ReloadG() error {
	if o == nil {
		return errors.New("models: no Platform provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Platform) Reload(exec boil.Executor) error {
	ret, err := FindPlatform(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *PlatformSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *PlatformSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PlatformSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty PlatformSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PlatformSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	platforms := PlatformSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), platformPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"platforms\".* FROM \"platforms\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, platformPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&platforms)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PlatformSlice")
	}

	*o = platforms

	return nil
}

// PlatformExists checks if the Platform row exists.
func PlatformExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"platforms\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if platforms exists")
	}

	return exists, nil
}

// PlatformExistsG checks if the Platform row exists.
func PlatformExistsG(id int) (bool, error) {
	return PlatformExists(boil.GetDB(), id)
}

// PlatformExistsGP checks if the Platform row exists. Panics on error.
func PlatformExistsGP(id int) bool {
	e, err := PlatformExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// PlatformExistsP checks if the Platform row exists. Panics on error.
func PlatformExistsP(exec boil.Executor, id int) bool {
	e, err := PlatformExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
