// This file is generated by SQLBoiler (https://github.com/vattle/sqlboiler)
// and is meant to be re-generated in place and/or deleted at any time.
// DO NOT EDIT

package models

import (
	"bytes"
	"database/sql"
	"fmt"
	"reflect"
	"strings"
	"sync"
	"time"

	"github.com/pkg/errors"
	"github.com/vattle/sqlboiler/boil"
	"github.com/vattle/sqlboiler/queries"
	"github.com/vattle/sqlboiler/queries/qm"
	"github.com/vattle/sqlboiler/strmangle"
	"github.com/vattle/sqlboiler/types"
	"gopkg.in/nullbio/null.v6"
)

// VulnInfo is an object representing the database table.
type VulnInfo struct {
	ID        int               `boil:"id" json:"id" toml:"id" yaml:"id"`
	CreatedAt null.Time         `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time         `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`
	DeletedAt null.Time         `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	CveID     null.String       `boil:"cve_id" json:"cve_id,omitempty" toml:"cve_id" yaml:"cve_id,omitempty"`
	CpeNames  types.StringArray `boil:"cpe_names" json:"cpe_names,omitempty" toml:"cpe_names" yaml:"cpe_names,omitempty"`

	R *vulnInfoR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L vulnInfoL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

// vulnInfoR is where relationships are stored.
type vulnInfoR struct {
}

// vulnInfoL is where Load methods for each relationship are stored.
type vulnInfoL struct{}

var (
	vulnInfoColumns               = []string{"id", "created_at", "updated_at", "deleted_at", "cve_id", "cpe_names"}
	vulnInfoColumnsWithoutDefault = []string{"created_at", "updated_at", "deleted_at", "cve_id", "cpe_names"}
	vulnInfoColumnsWithDefault    = []string{"id"}
	vulnInfoPrimaryKeyColumns     = []string{"id"}
)

type (
	// VulnInfoSlice is an alias for a slice of pointers to VulnInfo.
	// This should generally be used opposed to []VulnInfo.
	VulnInfoSlice []*VulnInfo
	// VulnInfoHook is the signature for custom VulnInfo hook methods
	VulnInfoHook func(boil.Executor, *VulnInfo) error

	vulnInfoQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	vulnInfoType                 = reflect.TypeOf(&VulnInfo{})
	vulnInfoMapping              = queries.MakeStructMapping(vulnInfoType)
	vulnInfoPrimaryKeyMapping, _ = queries.BindMapping(vulnInfoType, vulnInfoMapping, vulnInfoPrimaryKeyColumns)
	vulnInfoInsertCacheMut       sync.RWMutex
	vulnInfoInsertCache          = make(map[string]insertCache)
	vulnInfoUpdateCacheMut       sync.RWMutex
	vulnInfoUpdateCache          = make(map[string]updateCache)
	vulnInfoUpsertCacheMut       sync.RWMutex
	vulnInfoUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force bytes in case of primary key column that uses []byte (for relationship compares)
	_ = bytes.MinRead
)
var vulnInfoBeforeInsertHooks []VulnInfoHook
var vulnInfoBeforeUpdateHooks []VulnInfoHook
var vulnInfoBeforeDeleteHooks []VulnInfoHook
var vulnInfoBeforeUpsertHooks []VulnInfoHook

var vulnInfoAfterInsertHooks []VulnInfoHook
var vulnInfoAfterSelectHooks []VulnInfoHook
var vulnInfoAfterUpdateHooks []VulnInfoHook
var vulnInfoAfterDeleteHooks []VulnInfoHook
var vulnInfoAfterUpsertHooks []VulnInfoHook

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *VulnInfo) doBeforeInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range vulnInfoBeforeInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *VulnInfo) doBeforeUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range vulnInfoBeforeUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *VulnInfo) doBeforeDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range vulnInfoBeforeDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *VulnInfo) doBeforeUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range vulnInfoBeforeUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *VulnInfo) doAfterInsertHooks(exec boil.Executor) (err error) {
	for _, hook := range vulnInfoAfterInsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterSelectHooks executes all "after Select" hooks.
func (o *VulnInfo) doAfterSelectHooks(exec boil.Executor) (err error) {
	for _, hook := range vulnInfoAfterSelectHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *VulnInfo) doAfterUpdateHooks(exec boil.Executor) (err error) {
	for _, hook := range vulnInfoAfterUpdateHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *VulnInfo) doAfterDeleteHooks(exec boil.Executor) (err error) {
	for _, hook := range vulnInfoAfterDeleteHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *VulnInfo) doAfterUpsertHooks(exec boil.Executor) (err error) {
	for _, hook := range vulnInfoAfterUpsertHooks {
		if err := hook(exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddVulnInfoHook registers your hook function for all future operations.
func AddVulnInfoHook(hookPoint boil.HookPoint, vulnInfoHook VulnInfoHook) {
	switch hookPoint {
	case boil.BeforeInsertHook:
		vulnInfoBeforeInsertHooks = append(vulnInfoBeforeInsertHooks, vulnInfoHook)
	case boil.BeforeUpdateHook:
		vulnInfoBeforeUpdateHooks = append(vulnInfoBeforeUpdateHooks, vulnInfoHook)
	case boil.BeforeDeleteHook:
		vulnInfoBeforeDeleteHooks = append(vulnInfoBeforeDeleteHooks, vulnInfoHook)
	case boil.BeforeUpsertHook:
		vulnInfoBeforeUpsertHooks = append(vulnInfoBeforeUpsertHooks, vulnInfoHook)
	case boil.AfterInsertHook:
		vulnInfoAfterInsertHooks = append(vulnInfoAfterInsertHooks, vulnInfoHook)
	case boil.AfterSelectHook:
		vulnInfoAfterSelectHooks = append(vulnInfoAfterSelectHooks, vulnInfoHook)
	case boil.AfterUpdateHook:
		vulnInfoAfterUpdateHooks = append(vulnInfoAfterUpdateHooks, vulnInfoHook)
	case boil.AfterDeleteHook:
		vulnInfoAfterDeleteHooks = append(vulnInfoAfterDeleteHooks, vulnInfoHook)
	case boil.AfterUpsertHook:
		vulnInfoAfterUpsertHooks = append(vulnInfoAfterUpsertHooks, vulnInfoHook)
	}
}

// OneP returns a single vulnInfo record from the query, and panics on error.
func (q vulnInfoQuery) OneP() *VulnInfo {
	o, err := q.One()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// One returns a single vulnInfo record from the query.
func (q vulnInfoQuery) One() (*VulnInfo, error) {
	o := &VulnInfo{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for vuln_infos")
	}

	if err := o.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
		return o, err
	}

	return o, nil
}

// AllP returns all VulnInfo records from the query, and panics on error.
func (q vulnInfoQuery) AllP() VulnInfoSlice {
	o, err := q.All()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return o
}

// All returns all VulnInfo records from the query.
func (q vulnInfoQuery) All() (VulnInfoSlice, error) {
	var o []*VulnInfo

	err := q.Bind(&o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to VulnInfo slice")
	}

	if len(vulnInfoAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(queries.GetExecutor(q.Query)); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountP returns the count of all VulnInfo records in the query, and panics on error.
func (q vulnInfoQuery) CountP() int64 {
	c, err := q.Count()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return c
}

// Count returns the count of all VulnInfo records in the query.
func (q vulnInfoQuery) Count() (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count vuln_infos rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table, and panics on error.
func (q vulnInfoQuery) ExistsP() bool {
	e, err := q.Exists()
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// Exists checks if the row exists in the table.
func (q vulnInfoQuery) Exists() (bool, error) {
	var count int64

	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRow().Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if vuln_infos exists")
	}

	return count > 0, nil
}

// VulnInfosG retrieves all records.
func VulnInfosG(mods ...qm.QueryMod) vulnInfoQuery {
	return VulnInfos(boil.GetDB(), mods...)
}

// VulnInfos retrieves all the records using an executor.
func VulnInfos(exec boil.Executor, mods ...qm.QueryMod) vulnInfoQuery {
	mods = append(mods, qm.From("\"vuln_infos\""))
	return vulnInfoQuery{NewQuery(exec, mods...)}
}

// FindVulnInfoG retrieves a single record by ID.
func FindVulnInfoG(id int, selectCols ...string) (*VulnInfo, error) {
	return FindVulnInfo(boil.GetDB(), id, selectCols...)
}

// FindVulnInfoGP retrieves a single record by ID, and panics on error.
func FindVulnInfoGP(id int, selectCols ...string) *VulnInfo {
	retobj, err := FindVulnInfo(boil.GetDB(), id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// FindVulnInfo retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindVulnInfo(exec boil.Executor, id int, selectCols ...string) (*VulnInfo, error) {
	vulnInfoObj := &VulnInfo{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"vuln_infos\" where \"id\"=$1", sel,
	)

	q := queries.Raw(exec, query, id)

	err := q.Bind(vulnInfoObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from vuln_infos")
	}

	return vulnInfoObj, nil
}

// FindVulnInfoP retrieves a single record by ID with an executor, and panics on error.
func FindVulnInfoP(exec boil.Executor, id int, selectCols ...string) *VulnInfo {
	retobj, err := FindVulnInfo(exec, id, selectCols...)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return retobj
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *VulnInfo) InsertG(whitelist ...string) error {
	return o.Insert(boil.GetDB(), whitelist...)
}

// InsertGP a single record, and panics on error. See Insert for whitelist
// behavior description.
func (o *VulnInfo) InsertGP(whitelist ...string) {
	if err := o.Insert(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// InsertP a single record using an executor, and panics on error. See Insert
// for whitelist behavior description.
func (o *VulnInfo) InsertP(exec boil.Executor, whitelist ...string) {
	if err := o.Insert(exec, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Insert a single record using an executor.
// Whitelist behavior: If a whitelist is provided, only those columns supplied are inserted
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns without a default value are included (i.e. name, age)
// - All columns with a default, but non-zero are included (i.e. health = 75)
func (o *VulnInfo) Insert(exec boil.Executor, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no vuln_infos provided for insertion")
	}

	var err error
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	if o.UpdatedAt.Time.IsZero() {
		o.UpdatedAt.Time = currTime
		o.UpdatedAt.Valid = true
	}

	if err := o.doBeforeInsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vulnInfoColumnsWithDefault, o)

	key := makeCacheKey(whitelist, nzDefaults)
	vulnInfoInsertCacheMut.RLock()
	cache, cached := vulnInfoInsertCache[key]
	vulnInfoInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := strmangle.InsertColumnSet(
			vulnInfoColumns,
			vulnInfoColumnsWithDefault,
			vulnInfoColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		cache.valueMapping, err = queries.BindMapping(vulnInfoType, vulnInfoMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(vulnInfoType, vulnInfoMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"vuln_infos\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.IndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"vuln_infos\" DEFAULT VALUES"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		if len(wl) != 0 {
			cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into vuln_infos")
	}

	if !cached {
		vulnInfoInsertCacheMut.Lock()
		vulnInfoInsertCache[key] = cache
		vulnInfoInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(exec)
}

// UpdateG a single VulnInfo record. See Update for
// whitelist behavior description.
func (o *VulnInfo) UpdateG(whitelist ...string) error {
	return o.Update(boil.GetDB(), whitelist...)
}

// UpdateGP a single VulnInfo record.
// UpdateGP takes a whitelist of column names that should be updated.
// Panics on error. See Update for whitelist behavior description.
func (o *VulnInfo) UpdateGP(whitelist ...string) {
	if err := o.Update(boil.GetDB(), whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateP uses an executor to update the VulnInfo, and panics on error.
// See Update for whitelist behavior description.
func (o *VulnInfo) UpdateP(exec boil.Executor, whitelist ...string) {
	err := o.Update(exec, whitelist...)
	if err != nil {
		panic(boil.WrapErr(err))
	}
}

// Update uses an executor to update the VulnInfo.
// Whitelist behavior: If a whitelist is provided, only the columns given are updated.
// No whitelist behavior: Without a whitelist, columns are inferred by the following rules:
// - All columns are inferred to start with
// - All primary keys are subtracted from this set
// Update does not automatically update the record in case of default values. Use .Reload()
// to refresh the records.
func (o *VulnInfo) Update(exec boil.Executor, whitelist ...string) error {
	currTime := time.Now().In(boil.GetLocation())

	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	var err error
	if err = o.doBeforeUpdateHooks(exec); err != nil {
		return err
	}
	key := makeCacheKey(whitelist, nil)
	vulnInfoUpdateCacheMut.RLock()
	cache, cached := vulnInfoUpdateCache[key]
	vulnInfoUpdateCacheMut.RUnlock()

	if !cached {
		wl := strmangle.UpdateColumnSet(
			vulnInfoColumns,
			vulnInfoPrimaryKeyColumns,
			whitelist,
		)

		if len(whitelist) == 0 {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update vuln_infos, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"vuln_infos\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, vulnInfoPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(vulnInfoType, vulnInfoMapping, append(wl, vulnInfoPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, values)
	}

	_, err = exec.Exec(cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update vuln_infos row")
	}

	if !cached {
		vulnInfoUpdateCacheMut.Lock()
		vulnInfoUpdateCache[key] = cache
		vulnInfoUpdateCacheMut.Unlock()
	}

	return o.doAfterUpdateHooks(exec)
}

// UpdateAllP updates all rows with matching column names, and panics on error.
func (q vulnInfoQuery) UpdateAllP(cols M) {
	if err := q.UpdateAll(cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values.
func (q vulnInfoQuery) UpdateAll(cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for vuln_infos")
	}

	return nil
}

// UpdateAllG updates all rows with the specified column values.
func (o VulnInfoSlice) UpdateAllG(cols M) error {
	return o.UpdateAll(boil.GetDB(), cols)
}

// UpdateAllGP updates all rows with the specified column values, and panics on error.
func (o VulnInfoSlice) UpdateAllGP(cols M) {
	if err := o.UpdateAll(boil.GetDB(), cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAllP updates all rows with the specified column values, and panics on error.
func (o VulnInfoSlice) UpdateAllP(exec boil.Executor, cols M) {
	if err := o.UpdateAll(exec, cols); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o VulnInfoSlice) UpdateAll(exec boil.Executor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vulnInfoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"vuln_infos\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, vulnInfoPrimaryKeyColumns, len(o)))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in vulnInfo slice")
	}

	return nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *VulnInfo) UpsertG(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	return o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...)
}

// UpsertGP attempts an insert, and does an update or ignore on conflict. Panics on error.
func (o *VulnInfo) UpsertGP(updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(boil.GetDB(), updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// UpsertP attempts an insert using an executor, and does an update or ignore on conflict.
// UpsertP panics on error.
func (o *VulnInfo) UpsertP(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) {
	if err := o.Upsert(exec, updateOnConflict, conflictColumns, updateColumns, whitelist...); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
func (o *VulnInfo) Upsert(exec boil.Executor, updateOnConflict bool, conflictColumns []string, updateColumns []string, whitelist ...string) error {
	if o == nil {
		return errors.New("models: no vuln_infos provided for upsert")
	}
	currTime := time.Now().In(boil.GetLocation())

	if o.CreatedAt.Time.IsZero() {
		o.CreatedAt.Time = currTime
		o.CreatedAt.Valid = true
	}
	o.UpdatedAt.Time = currTime
	o.UpdatedAt.Valid = true

	if err := o.doBeforeUpsertHooks(exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(vulnInfoColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs postgres problems
	buf := strmangle.GetBuffer()

	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range updateColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range whitelist {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	vulnInfoUpsertCacheMut.RLock()
	cache, cached := vulnInfoUpsertCache[key]
	vulnInfoUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := strmangle.InsertColumnSet(
			vulnInfoColumns,
			vulnInfoColumnsWithDefault,
			vulnInfoColumnsWithoutDefault,
			nzDefaults,
			whitelist,
		)

		update := strmangle.UpdateColumnSet(
			vulnInfoColumns,
			vulnInfoPrimaryKeyColumns,
			updateColumns,
		)
		if len(update) == 0 {
			return errors.New("models: unable to upsert vuln_infos, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(vulnInfoPrimaryKeyColumns))
			copy(conflict, vulnInfoPrimaryKeyColumns)
		}
		cache.query = queries.BuildUpsertQueryPostgres(dialect, "\"vuln_infos\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(vulnInfoType, vulnInfoMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(vulnInfoType, vulnInfoMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, cache.query)
		fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRow(cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.Exec(cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert vuln_infos")
	}

	if !cached {
		vulnInfoUpsertCacheMut.Lock()
		vulnInfoUpsertCache[key] = cache
		vulnInfoUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(exec)
}

// DeleteP deletes a single VulnInfo record with an executor.
// DeleteP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *VulnInfo) DeleteP(exec boil.Executor) {
	if err := o.Delete(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteG deletes a single VulnInfo record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *VulnInfo) DeleteG() error {
	if o == nil {
		return errors.New("models: no VulnInfo provided for deletion")
	}

	return o.Delete(boil.GetDB())
}

// DeleteGP deletes a single VulnInfo record.
// DeleteGP will match against the primary key column to find the record to delete.
// Panics on error.
func (o *VulnInfo) DeleteGP() {
	if err := o.DeleteG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// Delete deletes a single VulnInfo record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *VulnInfo) Delete(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no VulnInfo provided for delete")
	}

	if err := o.doBeforeDeleteHooks(exec); err != nil {
		return err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), vulnInfoPrimaryKeyMapping)
	sql := "DELETE FROM \"vuln_infos\" WHERE \"id\"=$1"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args...)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from vuln_infos")
	}

	if err := o.doAfterDeleteHooks(exec); err != nil {
		return err
	}

	return nil
}

// DeleteAllP deletes all rows, and panics on error.
func (q vulnInfoQuery) DeleteAllP() {
	if err := q.DeleteAll(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all matching rows.
func (q vulnInfoQuery) DeleteAll() error {
	if q.Query == nil {
		return errors.New("models: no vulnInfoQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.Exec()
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from vuln_infos")
	}

	return nil
}

// DeleteAllGP deletes all rows in the slice, and panics on error.
func (o VulnInfoSlice) DeleteAllGP() {
	if err := o.DeleteAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAllG deletes all rows in the slice.
func (o VulnInfoSlice) DeleteAllG() error {
	if o == nil {
		return errors.New("models: no VulnInfo slice provided for delete all")
	}
	return o.DeleteAll(boil.GetDB())
}

// DeleteAllP deletes all rows in the slice, using an executor, and panics on error.
func (o VulnInfoSlice) DeleteAllP(exec boil.Executor) {
	if err := o.DeleteAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o VulnInfoSlice) DeleteAll(exec boil.Executor) error {
	if o == nil {
		return errors.New("models: no VulnInfo slice provided for delete all")
	}

	if len(o) == 0 {
		return nil
	}

	if len(vulnInfoBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vulnInfoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"vuln_infos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vulnInfoPrimaryKeyColumns, len(o))

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, args)
	}

	_, err := exec.Exec(sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from vulnInfo slice")
	}

	if len(vulnInfoAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(exec); err != nil {
				return err
			}
		}
	}

	return nil
}

// ReloadGP refetches the object from the database and panics on error.
func (o *VulnInfo) ReloadGP() {
	if err := o.ReloadG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadP refetches the object from the database with an executor. Panics on error.
func (o *VulnInfo) ReloadP(exec boil.Executor) {
	if err := o.Reload(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadG refetches the object from the database using the primary keys.
func (o *VulnInfo) ReloadG() error {
	if o == nil {
		return errors.New("models: no VulnInfo provided for reload")
	}

	return o.Reload(boil.GetDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *VulnInfo) Reload(exec boil.Executor) error {
	ret, err := FindVulnInfo(exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllGP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *VulnInfoSlice) ReloadAllGP() {
	if err := o.ReloadAllG(); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllP refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
// Panics on error.
func (o *VulnInfoSlice) ReloadAllP(exec boil.Executor) {
	if err := o.ReloadAll(exec); err != nil {
		panic(boil.WrapErr(err))
	}
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VulnInfoSlice) ReloadAllG() error {
	if o == nil {
		return errors.New("models: empty VulnInfoSlice provided for reload all")
	}

	return o.ReloadAll(boil.GetDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *VulnInfoSlice) ReloadAll(exec boil.Executor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	vulnInfos := VulnInfoSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), vulnInfoPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"vuln_infos\".* FROM \"vuln_infos\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, vulnInfoPrimaryKeyColumns, len(*o))

	q := queries.Raw(exec, sql, args...)

	err := q.Bind(&vulnInfos)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in VulnInfoSlice")
	}

	*o = vulnInfos

	return nil
}

// VulnInfoExists checks if the VulnInfo row exists.
func VulnInfoExists(exec boil.Executor, id int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"vuln_infos\" where \"id\"=$1 limit 1)"

	if boil.DebugMode {
		fmt.Fprintln(boil.DebugWriter, sql)
		fmt.Fprintln(boil.DebugWriter, id)
	}

	row := exec.QueryRow(sql, id)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if vuln_infos exists")
	}

	return exists, nil
}

// VulnInfoExistsG checks if the VulnInfo row exists.
func VulnInfoExistsG(id int) (bool, error) {
	return VulnInfoExists(boil.GetDB(), id)
}

// VulnInfoExistsGP checks if the VulnInfo row exists. Panics on error.
func VulnInfoExistsGP(id int) bool {
	e, err := VulnInfoExists(boil.GetDB(), id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}

// VulnInfoExistsP checks if the VulnInfo row exists. Panics on error.
func VulnInfoExistsP(exec boil.Executor, id int) bool {
	e, err := VulnInfoExists(exec, id)
	if err != nil {
		panic(boil.WrapErr(err))
	}

	return e
}
